# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d7db596d038a016a6bd2c96aca7c350aa40410d84c6e8551e5ec7521d7fbf4da090ea6ef6ddb27f4f58ea8f2a5e8d34d8eeeba6ecc37b146b9072c95f712904

test:
  secret_key_base: b193eb6fcfa915b42b7f390a4be109dd7dbf0b3f04595e746e010c47ec39f2f6927ed3dfe1008e281b1d2fa0cb51b5cfcfb8b6d95ae4d10dc0ce54a5c709431b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
